name: Auto merge

on:
  push:
    branches:
      - '*'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto-merge to main
        run: |
          git fetch origin
          git checkout main
          git merge origin/$(git rev-parse --abbrev-ref HEAD) --no-ff --commit
          git push origin main
